### ISSUE TITLE
Custom parse-method

### ISSUE THREAD

**Issue by kesla** [darkowlzz/simple-headers#1]
hey,

Saw that you're using my `parse-headers` module - which is great! But I see that you have a custom parse-method. Why is https://github.com/darkowlzz/simple-headers/blob/master/index.js#L50-L53 needed and would it make sense to add those lines to parse-headers instead?

**Comment by darkowlzz** [comment]
Hi @kesla,

I wrote `simple-headers` because I was in need of comparing header content. `parse-headers` when used to parse headers with HTTP version would convert "HTTP/1.1 200 OK" into 

`'http/1.1 200 ok': 'HTTP/1.1 200 OK'`

which wasn't useful. So I decided to get rid of this un-useful part and wrote a custom parse-method which would look for http version and remove that part from the header.

I don't think you need to include this behavior into `parse-headers`. I tailored it as per my need.

**Comment by kesla** [comment]
@darkowlzz Alright, thanks for exaining
